/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.Lista;
import java.util.Calendar;
import java.util.GregorianCalendar;
import modelo.Cuenta;
import modelo.CuentaAhorro;
import modelo.CuentaCorriente;
import modelo.CuentaInversion;
import static modelo.IFecha.ANO;
import static modelo.IFecha.DIA_DEL_MES;
import static modelo.IFecha.MES_DEL_ANO;

/**
 *
 * @author damar
 */
public class Visualizar extends javax.swing.JPanel {

    Lista lista;

    public Visualizar(Lista lis) {
        initComponents();

        botonanterior.setVisible(false);

        lista = lis;
        lis.setIndice(0);
        Cuenta actual = (Cuenta) lista.getVector()[lis.getIndice()].getDatos();
        cambiarDatos(actual);

    }
    
    public void cambiarDatos(Cuenta c){
        areanumero.setText(Integer.toString(c.getNumero()));
        if(c.getPropietario() == null){
            areapropietario.setText("********");
        }else{
            areapropietario.setText(c.getPropietario());
        }
        areasaldo.setText(Float.toString(c.getSaldo()));
        areasaldominimo.setText(Float.toString(c.getSaldominimo()));
        areafecha.setText(c.fechaString());
        
        if(c.getClass() == CuentaAhorro.class){
            CuentaAhorro cAux = (CuentaAhorro) c;
            ModificableTexto.setText("Interes Mensual:");
            ModificableBooleano.setText("Es Estudiante:");
            
            areaTexto.setVisible(true);
            areaBooleano.setVisible(true);
            
            areaTexto.setText(Float.toString(cAux.getInteresMensual()));
            if(cAux.isEstudiante())
                areaBooleano.setText("Si es.");
            else
                areaBooleano.setText("No es.");
            
        }else if(c.getClass() == CuentaCorriente.class){
            CuentaCorriente cAux = (CuentaCorriente) c;
            
            ModificableTexto.setText("Comision:");
            ModificableBooleano.setText("Tipo de Comision:");
            
            areaTexto.setVisible(true);
            areaBooleano.setVisible(true);
            
            areaTexto.setText(Float.toString(cAux.getComision()));
            if(cAux.isTipoComision())
                areaBooleano.setText("Semestral.");
            else
                areaBooleano.setText("Anual.");
            
            
        }else if(c.getClass() == CuentaInversion.class){
            CuentaInversion cAux = (CuentaInversion) c;
            ModificableTexto.setText("Beneficio:");
            ModificableBooleano.setText("Es Estudiante:");
            
            areaTexto.setVisible(true);
            areaBooleano.setVisible(true);
            
            areaTexto.setText(Float.toString(cAux.getBeneficio()));
            if(cAux.isEstudiante())
                areaBooleano.setText("Si es.");
            else
                areaBooleano.setText("No es.");
            
        }else{
            ModificableTexto.setText("******");
            ModificableBooleano.setText("******");
            areaTexto.setVisible(false);
            areaBooleano.setVisible(false);
        }
    }

    public void siguiente(Lista lista) {

        lista.setIndice(lista.getIndice() + 1);
        Cuenta actual = (Cuenta) lista.getVector()[lista.getIndice()].getDatos();

        cambiarDatos(actual);
        if (lista.getVector()[lista.getIndice() + 1] == null) {
            botonsiguiente.setVisible(false);
        }
        if (lista.getIndice() - 1 >= 0) {
            botonanterior.setVisible(true);
        }
    }
   
    public void anterior(Lista lista) {

        lista.setIndice(lista.getIndice() - 1);
        Cuenta actual = (Cuenta) lista.getVector()[lista.getIndice()].getDatos();

        cambiarDatos(actual);
        if (lista.getIndice() - 1 < 0) {
            botonanterior.setVisible(false);
        }
        if (lista.getVector()[lista.getIndice() + 1] != null) {
            botonsiguiente.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        areapropietario = new javax.swing.JTextField();
        areanumero = new javax.swing.JTextField();
        areafecha = new javax.swing.JTextField();
        areasaldo = new javax.swing.JTextField();
        areasaldominimo = new javax.swing.JTextField();
        areaTexto = new javax.swing.JTextField();
        areaBooleano = new javax.swing.JTextField();
        ModificableTexto = new javax.swing.JLabel();
        ModificableBooleano = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Calcular = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        botonsiguiente = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        botonanterior = new javax.swing.JButton();

        jLabel1.setText("Numero de Cuenta:");

        jLabel2.setText("Propietario:");

        jLabel3.setText("Saldo:");

        jLabel4.setText("Saldo Mínimo:");

        jLabel5.setText("Fecha:");

        areapropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areapropietarioActionPerformed(evt);
            }
        });

        areanumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areanumeroActionPerformed(evt);
            }
        });

        ModificableTexto.setText("*****");

        ModificableBooleano.setText("*****");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ModificableBooleano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(areaBooleano, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ModificableTexto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(areaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(areasaldominimo)
                            .addComponent(areanumero, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(areasaldo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(areapropietario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(areafecha, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(areanumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areapropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(areasaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(areasaldominimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(areafecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModificableTexto)
                    .addComponent(areaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areaBooleano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModificableBooleano))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Calcular.setText("Calcular");
        Calcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalcularMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(Calcular)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Calcular)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        botonsiguiente.setText("SIGUIENTE");
        botonsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonsiguiente)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonsiguiente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonanterior.setText("ANTERIOR");
        botonanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonanteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(botonanterior)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(botonanterior)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(0, 306, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 317, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 69, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonanteriorActionPerformed
        anterior(lista);
    }//GEN-LAST:event_botonanteriorActionPerformed

    private void botonsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsiguienteActionPerformed
        siguiente(lista);
    }//GEN-LAST:event_botonsiguienteActionPerformed

    private void areanumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areanumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areanumeroActionPerformed

    private void areapropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areapropietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areapropietarioActionPerformed

    private void CalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalcularMouseClicked
        Cuenta c = (Cuenta) lista.getVector()[lista.getIndice()].getDatos();
        GregorianCalendar calend = new GregorianCalendar();

        if (c.getClass() == CuentaAhorro.class) {
            CuentaAhorro cAux = (CuentaAhorro) c;
            
            //Mes

            if (((calend.get(MES_DEL_ANO) + 1) > cAux.mes() && calend.get(DIA_DEL_MES) >= cAux.dia() && calend.get(ANO) == cAux.ano()) || (calend.get(ANO) > cAux.ano())) {
                try{
                    cAux.setSaldo(cAux.getSaldo() + (cAux.getSaldo() * cAux.getInteresMensual() / 100));
                    lista.getVector()[lista.getIndice()].setDatos(cAux);
                } catch(Error e){
                    throw e;
                }
            }

        } else if (c.getClass() == CuentaCorriente.class) {
            CuentaCorriente cAux = (CuentaCorriente) c;
            
            // Semestre o Año para las cuentas corrientes

            if (((calend.get(MES_DEL_ANO) + 1) == cAux.mes() + 6 && calend.get(DIA_DEL_MES) >= cAux.dia() && calend.get(ANO) == cAux.ano()) || (calend.get(ANO) > cAux.ano())) {
                cAux.setSaldo(cAux.getSaldo() - cAux.getComision());
                
            }

        } else if (c.getClass() == CuentaInversion.class) {
            CuentaInversion cAux = (CuentaInversion) c;
            
            //Trimestres

            if (((calend.get(MES_DEL_ANO) + 1) >= cAux.mes() + 3 && calend.get(DIA_DEL_MES) >= cAux.dia() && calend.get(ANO) == cAux.ano()) || (calend.get(ANO) > cAux.ano())) {
                try{
                    cAux.setSaldo(cAux.getSaldo() + cAux.getBeneficio());
                    cAux.calculoBeneficio();
                    lista.getVector()[lista.getIndice()].setDatos(cAux);
                } catch(Error e){
                    throw e;
                }
            }
        }
        cambiarDatos((Cuenta) lista.getVector()[lista.getIndice()].getDatos());
    }//GEN-LAST:event_CalcularMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular;
    private javax.swing.JLabel ModificableBooleano;
    private javax.swing.JLabel ModificableTexto;
    private javax.swing.JTextField areaBooleano;
    private javax.swing.JTextField areaTexto;
    private javax.swing.JTextField areafecha;
    private javax.swing.JTextField areanumero;
    private javax.swing.JTextField areapropietario;
    private javax.swing.JTextField areasaldo;
    private javax.swing.JTextField areasaldominimo;
    private javax.swing.JButton botonanterior;
    private javax.swing.JButton botonsiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
