/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.Lista;
import modelo.Cuenta;
import modelo.CuentaAhorro;
import modelo.CuentaCorriente;

/**
 *
 * @author damar
 */
public class VisualizarLista extends javax.swing.JPanel {

    /**
     * Creates new form VisualizarLista
     */
    Lista lista;
    public VisualizarLista(Lista l) {
        
        lista=l;
        initComponents();
        
        String[] ncuentas = new String[lista.getVector().length];
        
    
        for(int i=0; lista.getVector()[i]!=null && i<lista.getVector().length;i++){
           
           Cuenta aux =(Cuenta) lista.getVector()[i].getDatos();
           String dat = (Integer.toString(aux.getNumero())+"; "+ aux.getPropietario()+", "+ Float.toString(aux.getSaldo()));
           
           if(aux.getClass() == CuentaAhorro.class){
               dat+=(" (Cuenta de ahorro)");
           }else if(aux.getClass() == CuentaCorriente.class){
               dat+=(" (Cuenta corriente)");

           }else{
               dat+=(" (Cuenta de inversion)");
           }
           ncuentas[i]=dat;
                   
        }
        Lista.setListData(ncuentas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Lista = new javax.swing.JList<>();

        Lista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(Lista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Lista;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
